spring:
  datasource:
    name: demo
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC#url
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:/resources/mapper/*.xml
  type-aliases-package: com.hengzhi.demo.bean

